---
title: AdamBate.com
baseURL: "/"
params:
  layout_style: grid
  palette: blue
  header:
    title: Adam Bate
    logo_img: ''
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links: []
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
